//武田佑樹 286120 課題1 (2)

public class MyName{
    public static void main(String[] args){
	
	//アスキーアート
	System.out.println("                                 xXXXX");
	System.out.println("                                  VXXXXXX");
	System.out.println("                                    VXXXXX      exxx");
	System.out.println("                                     VXXXXX       VXXXXXXe");
	System.out.println("                           xxxxx      VXXXX         VXXXXXXAx");
	System.out.println("             XXXXXXXXXXXXXXXXXXXXX    MXXXX            xXXXXV");
	System.out.println("              XXXXXXXXXXXXXXXXV        VXXXX             VXXV");
	System.out.println("                VXXXXXV                MXXXX");
	System.out.println("                                       MXXXX      eeexxxxXXXXXXxx");
	System.out.println("                                     xxxVXXXXXXXXXXXXXXXXXXXXXXXV");
	System.out.println("                            xxxXXXXXXXXXXXXXXXXXXXXXXV");
	System.out.println("    xXAxxx xAXXXXXXXXXXXXXXXXXXXXXXXXXX9 XXXXA");
	System.out.println("    VXXXXXXXXXXXXXXXXXXXXXXXV             MXXA");
	System.out.println("      VXXXXXXXXXV       VXXXXA            VXXXA");
	System.out.println("                        MXXXA              VXXXA");
	System.out.println("                        MXXXM               VXXXA");
	System.out.println("                        MXXXM     exxxxa     VXXXA ");
	System.out.println("          xXXxxx        MXXXMxXXXXXXXXXX0     VXXXA");
	System.out.println("            VXXXXA      MXXXXXXXXXXV           VXXXA");
	System.out.println("             AXXXM      MXXXV                   VXXXA");
	System.out.println("             MXXXM      MXXXM                    VXXXA");
	System.out.println("             MXXXM      MXXXM                     VXXXx");
	System.out.println("             VXXXM      MXXV          exxxx        VXXXAx           xx");
	System.out.println("             aMXXM      MXXM    exXXXXXv            VXXXXAe        aXa");
	System.out.println("              MXXM      MXXMXXXXXXXv                  VXXXXA      aXv");
	System.out.println("     ea       MXXMxXXXXXXXXXOV                         VXXXXXA   aXXN");
	System.out.println("     AXXXXXXXXXXXXXXXXXV                                 VXXXXXxeXXXN");
	System.out.println("      VXXXXXXXXXXxv                                        VXXXXXXXXN");
	System.out.println("        VXXXXA                                               VXXXXXXN");
	System.out.println("                                                               VXXXXN");
	System.out.println("                                                                   e ");
	System.out.println("");
	System.out.println("");
	System.out.println("");
	System.out.println("                                                      exxxxxXxxa");
	System.out.println("        eXXxxxx       eeeeexxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXA");
	System.out.println("         VXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXV         VXXXXXA");
	System.out.println("          VXXXXXaaaaav             VXXXXXA                   NXXXXXXV");
	System.out.println("           VXXXN                    VXXXN                     VXXXV");
	System.out.println("           NXXXN                    NXXXN                     AXXXN");
	System.out.println("            VXXN                    NXXXN                     NXXXV");
	System.out.println("            NXXNA                   NXXXN                     AXXXV");
	System.out.println("            VXXNA                   NXXXN                   eAXXXN");
	System.out.println("            NXXXN          exxxxxxxxNXXXNxxxxxxxxxxxxxxxxxxxxAXXXN");
	System.out.println("            VXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXN");
	System.out.println("            VXXXXXxxxv              NXXXN                    AXXXV");
	System.out.println("             NXXXN                  NXXXN                    AXXXV");
	System.out.println("             NXXXN                  NXXXN                   AXXXV");
	System.out.println("             NXXXN                  NXXXN                   NXXXN");
	System.out.println("             NXXXN                  NXXXN                   NXXXN");
	System.out.println("             NXXXN                  NXXXN                   NXXXV");
	System.out.println("             VXXXN                  NXXXV                   AXXV");
	System.out.println("             NXXXN              exxxNXXVxxxxxxxxxxxxxxxxxxxxXXXN");
	System.out.println("             VXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXN");
	System.out.println("              VXXXXXXXeeee                                 VXXXV");
	System.out.println("               VXV                                          VXV");
	System.out.println("");
	System.out.println("");
	System.out.println("");
	System.out.println("");
	System.out.println("");
	System.out.println("                    a                 aXxx");
	System.out.println("                    VXXAa              VXXXAx");
	System.out.println("                    AXXXXV              AXXXV");
	System.out.println("                    AXXXXV             AXXXV");
	System.out.println("                   AXXXV               NXXXV");
	System.out.println("                  AXXXV                AXXV");
	System.out.println("                 AXXXv                AXXXv                axe");
	System.out.println("                AXXXv                aXXXV      aaxxxxxXXXXXXXXAa");
	System.out.println("              aAXXV    aXaex       eXXXXXXxxxxxxxxxxxxxxxxxxxxxx");
	System.out.println("             AXXXV       VXXXXXXXXXXXXXXXaav");
	System.out.println("            AXXXXA           VXa   AXXXV");
	System.out.println("          aAXXXXXXN               aAXXV");
	System.out.println("        aAXXa VXXXV              aAXXV");
	System.out.println("       aAXv    AXX               AXXV");
	System.out.println("     aAXV     iAXN              AXXV");
	System.out.println("   aAV        iNXN             AXXV                   aXXaa");
	System.out.println("  av          iNXN            AXXVx        axxxxxXXXXXXXXXXXaa");
	System.out.println("              iNXN          aAXXXXXXXXXXXXXXXXXXXaav     VXXXXA");
	System.out.println("              iNXN         aAXV  VXXXA                   NXXXV");
	System.out.println("              iNXN        aAXV   vXXXA                  aXXXV");
	System.out.println("              iNXN      aAXV      VXXA                  AXXN");
	System.out.println("              INXN     AXV        VXXA                  AXXV");
	System.out.println("              AXXN   aAV          VXXXa                aAXN");
	System.out.println("             AXXXN aA              VXXN                AXXV");
	System.out.println("             NXXXN                 NXXN     aaaaaaaaaXXNXXV");
	System.out.println("             VXXXN                 vXXXXXXXXXXXXXXXXXXXXXXXv");
	System.out.println("              vXXv                  VXXaa");
	System.out.println("");
	System.out.println("");
	System.out.println("                                 aa");
	System.out.println("            aAXa                ZVXXXXXV                aXXXxa");
	System.out.println("             VXXXXAa              VXXXXN                  VXXXXxa");
	System.out.println("              VXXXXN               XXXN       aa           VXXXXV");
	System.out.println("               VXXXN               AXXN axXXXXXXXa         NXXXV");
	System.out.println("               NXXN      AXXXXXXXXXXXXXXXXaaav             NXXXN");
	System.out.println("               NXXN        VXXXXXXVXXXN                    NXXXN");
	System.out.println("               NXXNaAXAaa          NXXN                    NXXXN");
	System.out.println("  AXaaaaaaaAXXXXXXXXXXXXV          NXXNxxxxXXXAa           NXXXI axxXa");
	System.out.println("   aXXXXXXXXXXXXXXVa      a   aaaaXXXXXXXXXXXXXV           NXXXXXXXXXXV");
	System.out.println("      aaa    AXXXXNa      vVXXXXXXXxxv         VXXxxxXXXXXXXXXNaav");
	System.out.println("            aAXXXXXXXaa                         VXXXXxv    NXXXI  ");
	System.out.println("            AXXXXXN aXXA axa         axxxXXXxa             NXXXI");
	System.out.println("           AXXXXXXN VXXXv VXXXXXXXXXXXXXxXXXXXV            NXXXI");
	System.out.println("          AXXXxXXXN       NXXXN          AXXXXV ax         NXXXI");
	System.out.println("         AXXa NXXXI        VXXN          AXXXV   aAXa      NXXXI");
	System.out.println("        AXXV  NXXXI        NXXN          AXXV     VXXAa    NXXXI");
	System.out.println("       AXXV   NXXXI        VXXXXXXXXXXXXvaa        VXXXA   NXXXI");
	System.out.println("     aAXV     NXXXI         VXXXv     aAXVa         VXXXA  NXXXI");
	System.out.println("    aAXV      NXXXI      aa            AXXXAa        VXXV  NXXXI");
	System.out.println("   aXV        NXXN        AXXA         AXXXA               NXXXI");
	System.out.println("  aV          NXXN         VXXA       aAXXV                NXXXI");
	System.out.println("              NXXN          VXXA      aAXV     aaAa        NXXXI");
	System.out.println("              NXXN          NXXAa    AXXVaAXXXea           NXXXI");
	System.out.println("              NXXN    aa     VXXAaXXXXXXXXAa               NXXXI");
	System.out.println("             AXXXN   AXXXXXXXXXXXXXXXav             av     AXXXI");
	System.out.println("             AXXXN     VXXXXXXXXv                     VXXXXXXXXV");
	System.out.println("             aXXXa       aaa                            VXXXXXV");
	System.out.println("              aXV                                         VXXXV");
	System.out.println("                                                           VXV");

    }
}
